### PR TITLE
Support of recipient variables

### PR DESCRIPTION
**Pull request by NikitaRazmakhnin**
This should allow to send few personalized emails
interpolated by recipient variables (according to [documentation](https://documentation.mailgun.com/en/latest/user_manual.html#batch-sending)).

I have tested it with simple CLI small tool taken from [here](https://hackage.haskell.org/package/hailgun-send).

### CODE REVIEW

**Review by cevantes — APPROVED** [review]
All is good!

**Comment by ivb-supercede** [comment]
Shouldn't the presence of recipient variables also mean that the `To` field is replaced by `%recipient%`? (Or whatever the syntax is?)

I think it would also be good to add links to the documentation for recipient variables so we see how they can be used.

**Comment by NikitaRazmakhnin** [comment]
> Shouldn't the presence of recipient variables also mean that the `To` field is replaced by `%recipient%`? (Or whatever the syntax is?)

`To` field is unchanged: this is the place where you set emails where mail should be sent.
Variables are optionally used if they are presentend and if they are referenced: otherwise
Mailgun just sends a email with placeholders without interpolation if no variables presented.
It will be also personal emails but without interpolated values :)

> 
> I think it would also be good to add links to the documentation for recipient variables so we see how they can be used.

I thought its just enough to have a documentation in Mailgun, but not a big problem to add
an extra lines here as well: I just need to try to not directly repeat much of a mailgun doc 😄

**Comment by ivb-supercede** [comment]
>To field is unchanged: this is the place where you set emails where mail should be sent.
Variables are optionally used if they are presentend and if they are referenced: otherwise
Mailgun just sends a email with placeholders without interpolation if no variables presented.

How does Mailgun then know which recipient variable value to include in the email? If we have
```json
{ "alice@example.com": { "x": 1 }
, "bob@example.com": {"x": 2 }
}
```
And we interpolate `%recipient.x%`, which one gets chosen? I have the impression that it will send one email per recipient in the map, and so both Alice and Bob will get 2 emails if they are both in the `To` header?

>I thought its just enough to have a documentation in Mailgun

I agree, I feel just a link would be helpful so developers who don't know what recipient variables are can read about them.

**Comment by NikitaRazmakhnin** [comment]
@ivb-supercede everything is easy enough: Mailgun takes email by email from `To` array
and then just looks for placeholders. Then it extracts appropriate placeholders by email in map and renders
content only for that email and sends it :)

So for email to `alice@example.com` he will look into key inside of an subobject for key wit the that email and take `x = 1`.
Same for `bob@example.com` if he exists in `To` array.

In case if we omit sending of variables at all, then each person will just receive an email with placeholders `%recipient.{field}` :)

**Comment by ivb-supercede** [comment]
So one email will be sent per element of the `To` array if there are variables? I would appreciate some documentation of that. I thought the Mailgun docs were saying that using `%recipient%` in the `To` field was required.

**Comment by NikitaRazmakhnin** [comment]
> So one email will be sent per element of the `To` array if there are variables? I would appreciate some documentation of that. I thought the Mailgun docs were saying that using `%recipient%` in the `To` field was required.

@ivb-supercede 

Ah, looks like you are looking into section of `SMTP` sending? I see that in such setup
they use substitution from variables, since smtp does not allow to set array of recipients, only the bcc, I think :)

This is an example from documentation around of usage of HTTP API calls instead (which we are using currently):

```curl
curl -s --user 'api:YOUR_API_KEY' \
    https://api.mailgun.net/v3/YOUR_DOMAIN_NAME/messages \
    -F from='Excited User <YOU@YOUR_DOMAIN_NAME>' \
    -F to=alice@example.com \
    -F to=bob@example.com \
    -F recipient-variables='{"bob@example.com": {"first":"Bob", "id":1}, "alice@example.com": {"first":"Alice", "id": 2}}' \
    -F subject='Hey, %recipient.first%' \
    -F text='If you wish to unsubscribe, click http://mailgun/unsubscribe/%recipient.id%'
```
So here we have an ability to set array of emails recipients not using the bcc mechanism.

Am I right? :)

**Comment by NikitaRazmakhnin** [comment]
But actually I think that we are also allowed to use `%recipient%` even in HTTP API setup.
I just did not test it.

**Comment by ivb-supercede** [comment]
Ah yes, I think I misunderstood that Mailing Lists weren't required for the HTTP API, just for SMTP. Makes sense!

**Review by ivb-supercede — APPROVED** [review]

**Pull request merged**
